// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.example.tutorial;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface testOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // required int32 age = 2;
    boolean hasAge();
    int getAge();
  }
  public static final class test extends
      com.google.protobuf.GeneratedMessage
      implements testOrBuilder {
    // Use test.newBuilder() to construct.
    private test(Builder builder) {
      super(builder);
    }
    private test(boolean noInit) {}
    
    private static final test defaultInstance;
    public static test getDefaultInstance() {
      return defaultInstance;
    }
    
    public test getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.tutorial.Test.internal_static_tutorial_test_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.tutorial.Test.internal_static_tutorial_test_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 age = 2;
    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    public boolean hasAge() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getAge() {
      return age_;
    }
    
    private void initFields() {
      name_ = "";
      age_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAge()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, age_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.example.tutorial.Test.test parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.example.tutorial.Test.test parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.example.tutorial.Test.test parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.example.tutorial.Test.test parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.example.tutorial.Test.test parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.example.tutorial.Test.test parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.example.tutorial.Test.test parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.example.tutorial.Test.test parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.example.tutorial.Test.test parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.example.tutorial.Test.test parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.tutorial.Test.test prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.tutorial.Test.testOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.tutorial.Test.internal_static_tutorial_test_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.tutorial.Test.internal_static_tutorial_test_fieldAccessorTable;
      }
      
      // Construct using com.example.tutorial.Test.test.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.tutorial.Test.test.getDescriptor();
      }
      
      public com.example.tutorial.Test.test getDefaultInstanceForType() {
        return com.example.tutorial.Test.test.getDefaultInstance();
      }
      
      public com.example.tutorial.Test.test build() {
        com.example.tutorial.Test.test result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.example.tutorial.Test.test buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.example.tutorial.Test.test result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.example.tutorial.Test.test buildPartial() {
        com.example.tutorial.Test.test result = new com.example.tutorial.Test.test(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.age_ = age_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.tutorial.Test.test) {
          return mergeFrom((com.example.tutorial.Test.test)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.example.tutorial.Test.test other) {
        if (other == com.example.tutorial.Test.test.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasAge()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              age_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // required int32 age = 2;
      private int age_ ;
      public boolean hasAge() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getAge() {
        return age_;
      }
      public Builder setAge(int value) {
        bitField0_ |= 0x00000002;
        age_ = value;
        onChanged();
        return this;
      }
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:tutorial.test)
    }
    
    static {
      defaultInstance = new test(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tutorial.test)
  }
  
  public interface test2OrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .tutorial.test t = 1;
    java.util.List<com.example.tutorial.Test.test> 
        getTList();
    com.example.tutorial.Test.test getT(int index);
    int getTCount();
    java.util.List<? extends com.example.tutorial.Test.testOrBuilder> 
        getTOrBuilderList();
    com.example.tutorial.Test.testOrBuilder getTOrBuilder(
        int index);
  }
  public static final class test2 extends
      com.google.protobuf.GeneratedMessage
      implements test2OrBuilder {
    // Use test2.newBuilder() to construct.
    private test2(Builder builder) {
      super(builder);
    }
    private test2(boolean noInit) {}
    
    private static final test2 defaultInstance;
    public static test2 getDefaultInstance() {
      return defaultInstance;
    }
    
    public test2 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.tutorial.Test.internal_static_tutorial_test2_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.tutorial.Test.internal_static_tutorial_test2_fieldAccessorTable;
    }
    
    // repeated .tutorial.test t = 1;
    public static final int T_FIELD_NUMBER = 1;
    private java.util.List<com.example.tutorial.Test.test> t_;
    public java.util.List<com.example.tutorial.Test.test> getTList() {
      return t_;
    }
    public java.util.List<? extends com.example.tutorial.Test.testOrBuilder> 
        getTOrBuilderList() {
      return t_;
    }
    public int getTCount() {
      return t_.size();
    }
    public com.example.tutorial.Test.test getT(int index) {
      return t_.get(index);
    }
    public com.example.tutorial.Test.testOrBuilder getTOrBuilder(
        int index) {
      return t_.get(index);
    }
    
    private void initFields() {
      t_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getTCount(); i++) {
        if (!getT(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < t_.size(); i++) {
        output.writeMessage(1, t_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < t_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, t_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.example.tutorial.Test.test2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.example.tutorial.Test.test2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.example.tutorial.Test.test2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.example.tutorial.Test.test2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.example.tutorial.Test.test2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.example.tutorial.Test.test2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.example.tutorial.Test.test2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.example.tutorial.Test.test2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.example.tutorial.Test.test2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.example.tutorial.Test.test2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.tutorial.Test.test2 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.tutorial.Test.test2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.tutorial.Test.internal_static_tutorial_test2_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.tutorial.Test.internal_static_tutorial_test2_fieldAccessorTable;
      }
      
      // Construct using com.example.tutorial.Test.test2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (tBuilder_ == null) {
          t_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          tBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.tutorial.Test.test2.getDescriptor();
      }
      
      public com.example.tutorial.Test.test2 getDefaultInstanceForType() {
        return com.example.tutorial.Test.test2.getDefaultInstance();
      }
      
      public com.example.tutorial.Test.test2 build() {
        com.example.tutorial.Test.test2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.example.tutorial.Test.test2 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.example.tutorial.Test.test2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.example.tutorial.Test.test2 buildPartial() {
        com.example.tutorial.Test.test2 result = new com.example.tutorial.Test.test2(this);
        int from_bitField0_ = bitField0_;
        if (tBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            t_ = java.util.Collections.unmodifiableList(t_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.t_ = t_;
        } else {
          result.t_ = tBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.tutorial.Test.test2) {
          return mergeFrom((com.example.tutorial.Test.test2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.example.tutorial.Test.test2 other) {
        if (other == com.example.tutorial.Test.test2.getDefaultInstance()) return this;
        if (tBuilder_ == null) {
          if (!other.t_.isEmpty()) {
            if (t_.isEmpty()) {
              t_ = other.t_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTIsMutable();
              t_.addAll(other.t_);
            }
            onChanged();
          }
        } else {
          if (!other.t_.isEmpty()) {
            if (tBuilder_.isEmpty()) {
              tBuilder_.dispose();
              tBuilder_ = null;
              t_ = other.t_;
              bitField0_ = (bitField0_ & ~0x00000001);
              tBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTFieldBuilder() : null;
            } else {
              tBuilder_.addAllMessages(other.t_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getTCount(); i++) {
          if (!getT(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.example.tutorial.Test.test.Builder subBuilder = com.example.tutorial.Test.test.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addT(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .tutorial.test t = 1;
      private java.util.List<com.example.tutorial.Test.test> t_ =
        java.util.Collections.emptyList();
      private void ensureTIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          t_ = new java.util.ArrayList<com.example.tutorial.Test.test>(t_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.example.tutorial.Test.test, com.example.tutorial.Test.test.Builder, com.example.tutorial.Test.testOrBuilder> tBuilder_;
      
      public java.util.List<com.example.tutorial.Test.test> getTList() {
        if (tBuilder_ == null) {
          return java.util.Collections.unmodifiableList(t_);
        } else {
          return tBuilder_.getMessageList();
        }
      }
      public int getTCount() {
        if (tBuilder_ == null) {
          return t_.size();
        } else {
          return tBuilder_.getCount();
        }
      }
      public com.example.tutorial.Test.test getT(int index) {
        if (tBuilder_ == null) {
          return t_.get(index);
        } else {
          return tBuilder_.getMessage(index);
        }
      }
      public Builder setT(
          int index, com.example.tutorial.Test.test value) {
        if (tBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTIsMutable();
          t_.set(index, value);
          onChanged();
        } else {
          tBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setT(
          int index, com.example.tutorial.Test.test.Builder builderForValue) {
        if (tBuilder_ == null) {
          ensureTIsMutable();
          t_.set(index, builderForValue.build());
          onChanged();
        } else {
          tBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addT(com.example.tutorial.Test.test value) {
        if (tBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTIsMutable();
          t_.add(value);
          onChanged();
        } else {
          tBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addT(
          int index, com.example.tutorial.Test.test value) {
        if (tBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTIsMutable();
          t_.add(index, value);
          onChanged();
        } else {
          tBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addT(
          com.example.tutorial.Test.test.Builder builderForValue) {
        if (tBuilder_ == null) {
          ensureTIsMutable();
          t_.add(builderForValue.build());
          onChanged();
        } else {
          tBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addT(
          int index, com.example.tutorial.Test.test.Builder builderForValue) {
        if (tBuilder_ == null) {
          ensureTIsMutable();
          t_.add(index, builderForValue.build());
          onChanged();
        } else {
          tBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllT(
          java.lang.Iterable<? extends com.example.tutorial.Test.test> values) {
        if (tBuilder_ == null) {
          ensureTIsMutable();
          super.addAll(values, t_);
          onChanged();
        } else {
          tBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearT() {
        if (tBuilder_ == null) {
          t_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          tBuilder_.clear();
        }
        return this;
      }
      public Builder removeT(int index) {
        if (tBuilder_ == null) {
          ensureTIsMutable();
          t_.remove(index);
          onChanged();
        } else {
          tBuilder_.remove(index);
        }
        return this;
      }
      public com.example.tutorial.Test.test.Builder getTBuilder(
          int index) {
        return getTFieldBuilder().getBuilder(index);
      }
      public com.example.tutorial.Test.testOrBuilder getTOrBuilder(
          int index) {
        if (tBuilder_ == null) {
          return t_.get(index);  } else {
          return tBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.example.tutorial.Test.testOrBuilder> 
           getTOrBuilderList() {
        if (tBuilder_ != null) {
          return tBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(t_);
        }
      }
      public com.example.tutorial.Test.test.Builder addTBuilder() {
        return getTFieldBuilder().addBuilder(
            com.example.tutorial.Test.test.getDefaultInstance());
      }
      public com.example.tutorial.Test.test.Builder addTBuilder(
          int index) {
        return getTFieldBuilder().addBuilder(
            index, com.example.tutorial.Test.test.getDefaultInstance());
      }
      public java.util.List<com.example.tutorial.Test.test.Builder> 
           getTBuilderList() {
        return getTFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.example.tutorial.Test.test, com.example.tutorial.Test.test.Builder, com.example.tutorial.Test.testOrBuilder> 
          getTFieldBuilder() {
        if (tBuilder_ == null) {
          tBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.example.tutorial.Test.test, com.example.tutorial.Test.test.Builder, com.example.tutorial.Test.testOrBuilder>(
                  t_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          t_ = null;
        }
        return tBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:tutorial.test2)
    }
    
    static {
      defaultInstance = new test2(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tutorial.test2)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_test_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_test_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_test2_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_test2_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\010tutorial\"!\n\004test\022\014\n\004name\030\001" +
      " \002(\t\022\013\n\003age\030\002 \002(\005\"\"\n\005test2\022\031\n\001t\030\001 \003(\0132\016." +
      "tutorial.testB\034\n\024com.example.tutorialB\004T" +
      "est"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tutorial_test_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tutorial_test_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_test_descriptor,
              new java.lang.String[] { "Name", "Age", },
              com.example.tutorial.Test.test.class,
              com.example.tutorial.Test.test.Builder.class);
          internal_static_tutorial_test2_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_tutorial_test2_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_test2_descriptor,
              new java.lang.String[] { "T", },
              com.example.tutorial.Test.test2.class,
              com.example.tutorial.Test.test2.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
